# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
  - stage: build
    jobs:
    - job: run_build
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Assembly-Info-NetCore@2
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/*.csproj'
          InsertAttributes: false
          FileEncoding: 'auto'
          WriteBOM: false
          Authors: 'Maciej Małaszek'
          Product: 'GeneticToolkit'
          Copyright: 'Copyright © $(date:yyyy) Maciej Małaszek'
          PackageLicenseUrl: 'https://opensource.org/licenses/MIT'
          PackageProjectUrl: 'https://github.com/maciej-malaszek/GeneticToolkit'
          RepositoryUrl: 'https://github.com/maciej-malaszek/GeneticToolkit'
          RepositoryType: 'GIT'
          VersionNumber: '$(Version)$(Rev:.r)'
          FileVersionNumber: '$(Version)$(Rev:.r)'
          InformationalVersion: '$(Version)$(Rev:.r)'
          PackageVersion: '$(Version)$(Rev:.r)'
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false
      - task: DotNetCoreCLI@2
        inputs:
          command: test
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/GeneticToolkit.csproj'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'genetic-toolkit'
          publishLocation: 'Container'
