# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
variables:
  buildConfiguration: 'Release'
  Version: '0.3'
stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: 'Run Build'
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: gitversion/setup@0
        inputs:
          versionSpec: '5.x'
      - task: gitversion/execute@0

      - task: Assembly-Info-NetCore@2
        inputs:
          Path: '$(Build.SourcesDirectory)'
          FileNames: '**/*.csproj'
          InsertAttributes: false
          FileEncoding: 'auto'
          WriteBOM: false
          Authors: 'Maciej Małaszek'
          Product: 'GeneticToolkit'
          Copyright: 'Copyright © $(date:yyyy) Maciej Małaszek'
          PackageLicenseUrl: 'https://opensource.org/licenses/MIT'
          PackageProjectUrl: 'https://github.com/maciej-malaszek/GeneticToolkit'
          RepositoryUrl: 'https://github.com/maciej-malaszek/GeneticToolkit'
          RepositoryType: 'GIT'
          VersionNumber: '$(GitVersion.AssemblySemVer)'
          FileVersionNumber: '$(GitVersion.AssemblySemVer)'
          InformationalVersion: '$(GitVersion.AssemblySemVer)'
          PackageVersion: '$(GitVersion.AssemblySemVer)'
          LogLevel: 'verbose'
          FailOnWarning: false
          DisableTelemetry: false
      - task: DotNetCoreCLI@2
        inputs:
          command: test
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
          projects: '**/GeneticToolkit.csproj'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'genetic-toolkit'
          publishLocation: 'Container'

  - stage: GithubRelease
    displayName: 'GitHub Release'
    dependsOn: Build
    pool:
      vmImage: ubuntu-latest
    jobs:
      - deployment: DeploySolution
        displayName: 'Deploy Solution'
        environment: Production
        strategy:
         runOnce:
           deploy:
             steps:
             - task: GitHubRelease@1
               inputs:
                 gitHubConnection: 'GitHub Connection'
                 repositoryName: 'maciej-malaszek/GeneticToolkit'
                 action: 'create'
                 target: '$(Build.SourceVersion)'
                 tagSource: 'userSpecifiedTag'
                 tag: '$(GitVersion.SemVer)'
                 changeLogCompareToRelease: 'lastFullRelease'
                 changeLogType: 'commitBased'